
spring:
  data:
      elasticsearch:
        cluster-name: es-cluster
        cluster-nodes: 47.107.168.169:9300
  rabbitmq:
      host: 47.112.202.147
      username: guest
      password: guest
      port: 5672
  redis:
      host: 47.112.202.147
#debug: true
