
spring:
  data:
      elasticsearch:
        cluster-name: es-cluster
        cluster-nodes: 127.0.0.1:9300
  rabbitmq:
      host: 127.0.0.1
      username: guest
      password: guest
      port: 5672
  redis:
      host: 127.0.0.1
#debug: true
